# Generated by Django 4.1.1 on 2022-09-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news_generated_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
