# Generated by Django 4.1.1 on 2022-09-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news_generated_data', '0002_alter_news_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='parts',
        ),
        migrations.DeleteModel(
            name='relations',
        ),
    ]
