# Generated by Django 4.1.1 on 2022-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news_generated_data', '0003_remove_news_parts_delete_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
