# Generated by Django 4.1.1 on 2022-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_added_data', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
