# Generated by Django 4.1.1 on 2022-09-19 10:31

from django.db import migrations, models
import user_added_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_added_data', '0005_alter_userposts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='id',
            field=models.BigAutoField(default=user_added_data.models.createID, primary_key=True, serialize=False, unique=True),
        ),
    ]
