# Generated by Django 4.1.1 on 2022-09-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_added_data', '0006_alter_userposts_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name',)},
        ),
    ]
