# Generated by Django 4.1.1 on 2022-09-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_added_data', '0007_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
